---
- name: Create database working directory
  file:
    path: /opt/fitonduty-db
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'

- name: Install system Python dependencies
  apt:
    name:
      - python3-venv
      - python3-pip
      - python3-dev
    state: present
    update_cache: yes

- name: Create virtual environment for database management
  command: python3 -m venv /opt/fitonduty-db/venv
  args:
    creates: /opt/fitonduty-db/venv/bin/python
  become_user: postgres

- name: Upgrade pip in virtual environment
  pip:
    name: pip
    virtualenv: /opt/fitonduty-db/venv
    state: latest

- name: Install Python dependencies in virtual environment
  pip:
    name:
      - sqlalchemy>=2.0.0
      - psycopg2-binary
      - pyyaml
      - werkzeug
      - python-dotenv
    virtualenv: /opt/fitonduty-db/venv
    state: present

- name: Copy database management script
  copy:
    src: "{{ playbook_dir }}/../../python/db_manager.py"
    dest: /opt/fitonduty-db/db_manager.py
    owner: postgres
    group: postgres
    mode: '0755'

- name: Copy sql function generator
  copy:
    src: "{{ playbook_dir }}/../../python/migration_runner.py"
    dest: /opt/fitonduty-db/migration_runner.py
    owner: postgres
    group: postgres
    mode: '0755'

- name: Copy database schema files
  copy:
    src: "{{ playbook_dir }}/../../schema/"
    dest: /opt/fitonduty-db/schema/
    owner: postgres
    group: postgres
    mode: '0644'

- name: Copy environment configuration
  copy:
    src: "{{ playbook_dir }}/../../config/environments/{{ db_environment }}.yml"
    dest: /opt/fitonduty-db/db_config.yml
    owner: postgres
    group: postgres
    mode: '0644'

- name: Copy seed data configuration
  copy:
    src: "{{ playbook_dir }}/../../config/seed-data/{{ db_environment }}_seed.yml"
    dest: /opt/fitonduty-db/db_seed.yml
    owner: postgres
    group: postgres
    mode: '0644'

- name: Initialize database schema as postgres user
  command: >
    /opt/fitonduty-db/venv/bin/python /opt/fitonduty-db/db_manager.py
    --db-url "postgresql://postgres:{{ vault_postgres_password }}@localhost:5432/{{ fitonduty_db_name }}"
    --config /opt/fitonduty-db/db_seed.yml
    --seed
    --set-permissions
    --drop
  become_user: postgres
  environment:
    DB_ENVIRONMENT: "{{ db_environment }}"
  register: db_init_result
  changed_when: "'successfully' in db_init_result.stdout"

- name: 
  command: >
    /opt/fitonduty-db/venv/bin/python /opt/fitonduty-db/migration_runner.py
    --db-url "postgresql://postgres:{{ vault_postgres_password }}@localhost:5432/{{ fitonduty_db_name }}"
    --project-root /opt/fitonduty-db
  become_user: postgres
  environment:
    DB_ENVIRONMENT: "{{ db_environment }}"
  register: db_init_result
  changed_when: "'successfully' in db_init_result.stdout"

- name: Transfer ownership of all database objects to admin user
  postgresql_query:
    login_db: "{{ fitonduty_db_name }}"
    login_user: postgres
    login_password: "{{ vault_postgres_password }}"
    query: |
      -- Transfer database ownership
      ALTER DATABASE {{ fitonduty_db_name }} OWNER TO {{ fitonduty_admin_user }};
      
      -- Transfer all table ownership
      DO $$
      DECLARE
          r RECORD;
      BEGIN
          FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
          LOOP
              EXECUTE 'ALTER TABLE public.' || quote_ident(r.tablename) || ' OWNER TO {{ fitonduty_admin_user }}';
          END LOOP;
      END $$;
      
      -- Transfer all sequence ownership
      DO $$
      DECLARE
          r RECORD;
      BEGIN
          FOR r IN SELECT sequencename FROM pg_sequences WHERE schemaname = 'public'
          LOOP
              EXECUTE 'ALTER SEQUENCE public.' || quote_ident(r.sequencename) || ' OWNER TO {{ fitonduty_admin_user }}';
          END LOOP;
      END $$;
      
      -- Grant schema privileges
      GRANT ALL ON SCHEMA public TO {{ fitonduty_admin_user }};
      GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ fitonduty_admin_user }};
      GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{ fitonduty_admin_user }};
  become_user: postgres