---
- name: Setup FitonDuty Database Infrastructure
  hosts: database_servers
  become: yes
  vars:
    database_name: "{{ fitonduty_db_name }}"
    admin_user: "{{ fitonduty_admin_user }}"
    admin_password: "{{ vault_admin_password }}"
    postgres_password: "{{ vault_postgres_password | default('') }}"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - postgresql
    - fitonduty_database

  post_tasks:
    - name: Verify database setup
      postgresql_query:
        db: "{{ database_name }}"
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_password }}"
        query: "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'"
      register: table_count
      
    - name: Display setup summary
      debug:
        msg: |
          Database setup complete for {{ db_environment }}:
          - Database: {{ database_name }}
          - Admin user: {{ admin_user }}
          - Tables created: {{ table_count.query_result[0][0] if table_count.query_result else 'N/A' }}